metadata:
  identification:
    title: pygeoapi OGC API - Processes
    description: Provide an OGC API - Processes service using pygeoapi
    keywords:
        - ogc
        - process
        - api
    keywords_type: theme  # keyword type as per the ISO 19115 MD_KeywordTypeCode codelist. Accepted values are discipline, temporal, place, theme, stratum
    terms_of_service: https://creativecommons.org/licenses/by/4.0/  # terms of service
    url: https://example.org  # informative URL about the service
  license:  # licensing details
      name: CC-BY 4.0 license
      url: https://creativecommons.org/licenses/by/4.0/
  provider:  # service provider details
      name: Organization Name
      url: https://pygeoapi.io
  contact:  # service contact details
      name: Jérémie Durand
      position: Intern 
      address: X
      city: X
      stateorprovince: X
      postalcode: X
      country: Canada
      phone: +xx-xxx-xxx-xxxx
      fax: +xx-xxx-xxx-xxxx
      email: durj1104@usherbrooke.ca
      url: X
      hours: X
      instructions: X
      role: X

resources:
  hello-world-pygeoapi:
    type: process
    title: Hello World Process pygeoapi basic
    description: A simple process that returns a welcome message.
    processor:
      name: pygeoapi.process.hello_world.HelloWorldProcessor # basic pygeoapi process
  
  mycool-process:
    type: process
    title: My custom Process
    description: A simple process that returns the square root of a number.
    processor:
      name: processes.demo.mycool_process.MyCoolSqrtProcessor # custom process from mycool_process.py

server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json
  encoding: utf-8
  language: en-US

logging:
  level: DEBUG
  logfile: /tmp/pygeoapi.log

manager:
  name: Dummy
  connection:
    subscribers:
      - in_progress_uri: http://localhost:5000/status/in-progress
        success_uri: http://localhost:5000/status/success
        failed_uri: http://localhost:5000/status/failed