[pytest]
testpaths = test
markers =
    unit: unit tests
    integration: integration tests
    mocked: tests with mocked external services
addopts = --import-mode=importlib
filterwarnings =
    ignore::DeprecationWarning:stac_fastapi
    ignore::fastapi.exceptions.FastAPIDeprecationWarning
