[pytest]
testpaths =
    gis-pipeline/test
    stac-api/test
    vector-api/test
    raster-api/test
    pygeoapi/test
markers =
    unit: unit tests
    integration: integration tests
    mocked: tests with mocked external services
addopts = --import-mode=importlib
pythonpath =
    gis-pipeline/src
    stac-api/src
    vector-api/src
    raster-api/src
    pygeoapi/src