import os
from pathlib import Path

# Pin help width so local and CI runs produce byte-identical output
os.environ["COLUMNS"] = "80"

from gis_pipeline.main import parse_args

parser = parse_args(return_parser=True)

candidate_paths = [
    Path("/app/docs/ARGS.md"),  # docker path (mounted via docker-compose)
    Path(__file__).resolve().parents[2] / "docs" / "ARGS.md",  # local path
]

args_md_path = next((p for p in candidate_paths if p.parent.exists()), None)
script_name = Path(__file__).name if __file__ else "generate_args_md.py"

with args_md_path.open("w") as f:
    f.write("## Pipeline Command-Line Arguments\n\n")
    f.write(
        f"Note: Auto-generated by {script_name} — do not edit directly. "
        "After changing CLI args, regenerate with `make generate-args` "
        "(CI fails if out of sync).\n\n"
    )
    f.write("| Argument | Description |\n")
    f.write("|----------|-------------|\n")
    for action in parser._actions:
        if action.option_strings:
            opts = ", ".join(action.option_strings)
            desc = action.help or ""
            f.write(f"| `{opts}` | {desc} |\n")

    # Add the auto-generated help output
    f.write("\n\n## `--help` Output\n\n")
    f.write("```bash\n")
    f.write(parser.format_help())
    f.write("```\n")

print(f"ARGS.md generated at {args_md_path.resolve()}")
