[pytest]
testpaths = test
markers =
    unit: unit tests
    integration: integration tests
    mocked: tests with mocked external services
addopts = --import-mode=importlib
pythonpath = processes
filterwarnings =
    ignore::DeprecationWarning:webob
