window.GROPRO_LABELS = {
    AUT: 'Autres',
    AVO: 'Avoine',
    BPA: 'Blé, triticale, épeautre',
    CMA: 'CMA-Multiples',
    CNL: 'Canola',
    DIV: 'CMA-Légumes divers',
    FEU: 'CMA-Feuillus',
    FOI: 'Foin',
    FRU: 'CMA-Fruits',
    INC: 'Inconnu',
    LDT: 'Légumes de transformation',
    MAF: 'Maïs fourrager',
    MGR: 'Maïs-grain',
    MUL: 'Multiples',
    ORG: 'Orge',
    PDT: 'Pommes de terre',
    POM: 'Pommes',
    PRT: 'Protéagineuses',
    PTF: 'Petits fruits',
    RAC: 'CMA-Racines',
    SEI: 'Seigle',
    SOY: 'Soya',
    VIV: 'CMA-Vivaces'
};
