FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    gdal-bin libgdal-dev python3-dev \
    proj-bin proj-data \
    && rm -rf /var/lib/apt/lists/*

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV PROJ_LIB=/usr/share/proj

WORKDIR /app

# Copier les fichiers dans le conteneur
COPY requirements.txt .
COPY test/main.py .
COPY test/init_postgis.py .
COPY test/processing_stac.py .

# Installer les dépendances Python
RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]