ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

# Set environment variables
ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ENV MODULE_NAME=stac_fastapi.pgstac.app
ENV VARIABLE_NAME=app

# Copy requirements and scripts
COPY requirements-stac.txt .
COPY dockerfiles/scripts/wait-for-it.sh /tmp/scripts/wait-for-it.sh

# Install dependencies and setup scripts
RUN chmod +x /tmp/scripts/wait-for-it.sh && \
    python -m pip install --no-cache-dir -r requirements-stac.txt && \
    rm -rf /tmp/* /var/tmp/*