FROM osgeo/gdal:ubuntu-small-3.6.2

WORKDIR /app

# Installer pip et dépendances Python
RUN apt-get update && apt-get install -y python3-pip && \
    pip install --upgrade pip setuptools wheel

# Copier les dépendances et les installer
COPY requirements-python.txt ./
RUN pip install --no-cache-dir --resume-retries=5 -r requirements-python.txt

COPY dockerfiles/scripts/wait-for-it.sh /tmp/scripts/wait-for-it.sh
RUN chmod +x /tmp/scripts/wait-for-it.sh

# Éviter les connexions réseau de PROJ à runtime
ENV PROJ_NETWORK=OFF

# Copier tous les fichiers nécessaires
COPY test/*.py ./

# Lancer l'application
CMD ["python3", "main.py"]