ARG PYTHON_VERSION=3.11

FROM ghcr.io/vincentsarago/uvicorn-gunicorn:${PYTHON_VERSION}

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

COPY dockerfiles/scripts/wait-for-it.sh /tmp/scripts/wait-for-it.sh
RUN chmod +x /tmp/scripts/wait-for-it.sh

# Install system dependencies
COPY requirements-stac.txt .
RUN python -m pip install --no-cache-dir -r requirements-stac.txt

ENV MODULE_NAME stac_fastapi.pgstac.app
ENV VARIABLE_NAME app
