FROM python:3.11-slim

# Set environment variables
ENV PYTHONPATH=/app

# Set the working directory
WORKDIR /app

# Copy requirements
COPY requirements-duckdb.txt ./

# Install dependencies and create data directory
RUN pip install --no-cache-dir -r requirements-duckdb.txt && \
    mkdir -p /app/data && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy application files
COPY infrastructure/duckdb /app/infrastructure/duckdb
COPY demo /app/demo

# Default command to run the application
CMD ["python3", "infrastructure/duckdb/app.py"]