FROM osgeo/gdal:ubuntu-small-3.6.2

# Set environment variables
ENV PROJ_NETWORK=OFF
ENV PYTHONPATH=/app

# Set the working directory
WORKDIR /app

# Copy requirements
COPY requirements-python.txt ./requirements-python.txt
COPY requirements-duckdb.txt ./requirements-duckdb.txt
COPY dockerfiles/scripts/wait-for-it.sh /tmp/scripts/wait-for-it.sh

# Install dependencies, create directories, and setup scripts
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir --resume-retries=5 \
        -r requirements-python.txt \
        -r requirements-duckdb.txt && \
    chmod +x /tmp/scripts/wait-for-it.sh && \
    mkdir -p /app/data && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy application files
COPY demo /app/demo
COPY infrastructure/duckdb /app/infrastructure/duckdb
COPY tests /app/tests

# Default entrypoint
CMD ["python3", "-m demo.main"]